name: Test Docs Build

on:
  pull_request:
    paths:
      - 'docs/**'
      - '**.md'
      - '**.rst'
      - '**.txt'

permissions:
  contents: read

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: 'pip'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install sphinx sphinx_rtd_theme
          if [ -f docs/requirements.txt ]; then pip install -r docs/requirements.txt; fi
          
      - name: Build documentation
        run: |
          sphinx-build -b html docs docs/_build/html
          
      - name: Check build result
        run: |
          if [ -d docs/_build/html ]; then
            echo "Documentation built successfully!"
          else
            echo "Documentation build failed!"
            exit 1
          fi
